### PR TITLE
Add ci

### PR DESCRIPTION
**Pull request by patrickelectric**
image

Please, if possible, can you guys create a release with the binaries ?

### CODE REVIEW

**Comment by patrickelectric** [comment]
ping @fuzzypixelz

**Comment by fuzzypixelz** [comment]
While I wasn't expecting anyone to be using this fork, I understand the utility of having binaries.

However, this workflow would need to use self hosted runners instead of the GitHub-hosted ones. I would also only run it on `release`.

Thanks for the pull request!

**Comment by patrickelectric** [comment]
@fuzzypixelz 

1. Why does it need self-hosted runners ? You can check my own action running in my fork and it just works, it uses cross to build the binaries, not custom runner.
2. It generates artifacts per action besides the binaries in releases as well, there is also a release from april from this same fork. So I don't understand your point.
3. This fork names "toml-cli2" so I believed that this is an intended work to be maintained, or am I wrong ?

**Comment by gabrik** [comment]
Hi, @patrickelectric, GitHub runners have a cost, and it's company policy to not use them unless required for repo in this organization.

So if you really need this to run we can change the CI to match our runners.

Are you ok with us committing to your PR?

**Comment by patrickelectric** [comment]
Hi @gabrik, thanks for clarifying it. GitHub runners indeed are free, but the build minutes are limited for sure. Be free to modify the PR as necessary to run in your self-hosted runners.

**Comment by patrickelectric** [comment]
Hi @gabrik any update on that ?

**Pull request merged**
